name: "Cave Paintings"
markdown: kramdown
permalink: "/:tags/:title/"  # Ensure the permalink ends with a slash for proper URL structure
paginate: 1  # One post per page is correct
paginate_path: "/:tags/:num/"  # Correct format for numeric pagination within each tag
baseurl: "/cave"  # Base URL for a site hosted at /cave/
